all:
  hosts:
    vm1:
      ansible_host: 192.168.8.110
    vm2:
      ansible_host: 192.168.8.120
    vm3:
      ansible_host: 192.168.8.130
  vars:
    ansible_user: hendi
    ansible_ssh_private_key_file: ~/.ssh/id_homelab